[System.Serializable]
public enum UI_Tabs
{
    LOGIN_SCREEN,
    MAIN_MENU_STUDENT_SCREEN,
    MAIN_MENU_TEACHER_SCREEN,
    INSTRUCTIONS_SCREEN,
    STUDENT_GRADES_SCREEN,
    DIFFICULTY_SELECT_SCREEN,
    QUIT
}
